### PR TITLE
Create __init__.py

### PR DESCRIPTION
**Pull request by Adibvafa**
# PR Type ([Feature | Fix | Documentation | Test])
Fix the issue of importing MortalityPredictionTask. Source of the bug is when replication the tutorial below: https://vectorinstitute.github.io/cyclops/api/tutorials/kaggle/heart_failure_prediction.html

## Short Description
The following code fails because 'tasks' will be loaded as 'tasks.py' file instead of the directory containing 'mortalitiy_prediction'.

from cyclops.tasks.mortality_prediction import MortalityPredictionTask

## Tests Added
Added init file to fix the issue.

### CODE REVIEW

**Comment by fcogidi** [comment]
Thanks for your contribution! :)

Could you share how you set up your environment? Was it through the pip install?

I ask because running `from cyclops.tasks.mortality_prediction import MortalityPredictionTask` doesn't fail in my environment. But that's a development environment.

**Comment by amrit110** [comment]
Yeah adding to @fcogidi, good catch. In the development env, poetry installs the `cyclops` package which adds the package directory to the `PYTHONPATH` which allows for discovery of subpackages and modules.  

BTW, we could even import the task classes in the init file so that you can do `from cyclops.tasks import MortalityPredictionTask`. @Adibvafa could you add that to the __init__file? So:

```python
from cyclops.tasks.mortality_prediction import MortalityPredictionTask
from cyclops.tasks.cxr_classification import CXRClassificationTask
```

**Comment by Adibvafa** [comment]
> Thanks for your contribution! :)
> 
> Could you share how you set up your environment? Was it through the pip install?
> 
> I ask because running `from cyclops.tasks.mortality_prediction import MortalityPredictionTask` doesn't fail in my environment. But that's a development environment.

Yes, my environment is not a development environment, it's merely a conda env and I installed cyclops with pip.

**Comment by Adibvafa** [comment]
> Yeah adding to @fcogidi, good catch. In the development env, poetry installs the `cyclops` package which adds the package directory to the `PYTHONPATH` which allows for discovery of subpackages and modules.
> 
> BTW, we could even import the task classes in the init file so that you can do `from cyclops.tasks import MortalityPredictionTask`. @Adibvafa could you add that to the __init__file? So:
> 
> ```python
> from cyclops.tasks.mortality_prediction import MortalityPredictionTask
> from cyclops.tasks.cxr_classification import CXRClassificationTask
> ```

That's a great idea! Just committed the changes you mentioned.

**Review by amrit110 — APPROVED** [review]

**Comment by amrit110** [comment]
@Adibvafa, should now be fixed in `v0.1.38`, so just update the pip install :).

**Comment by Adibvafa** [comment]
> @Adibvafa, should now be fixed in `v0.1.38`, so just update the pip install :).

Awesome! Thank you so much!

**Pull request merged**
