### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by amrit110**
# PR Type ([Feature | Fix | Documentation | Test])
Dependencies

## Short Description
...

## Tests Added
...

### CODE REVIEW

**Comment by amrit110** [comment]
@fcogidi, there seems to be some error ``ImportError: cannot import name '_is_numpy_array' from 'array_api_compat.common._helpers`` thats now breaking the main branch. Could you please help debug this? Not sure if the API of ``array-api-compat`` changed.

**Comment by fcogidi** [comment]
> @fcogidi, there seems to be some error `ImportError: cannot import name '_is_numpy_array' from 'array_api_compat.common._helpers` thats now breaking the main branch. Could you please help debug this? Not sure if the API of `array-api-compat` changed.

Yeah, they recently updated to a new version. Since we have `^1.4` in poetry, it installed `v1.5`, which is the new one that likely has breaking changes.

**Comment by amrit110** [comment]
Weirdly, if you see the poetry.lock file on main, it still says 1.4. But the recent CI on main broke as well.

**Comment by amrit110** [comment]
@fcogidi , you're right for some reason, the package install checks when it does `pip install -e .` it installs the 1.5 version. I thought pip will consider the `poetry.lock` file but apparently it doesn't. will have to fix that in a later PR. For now, im just fixing the array-api-compat version to 1.4.

**Pull request merged**
